config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    resources :articles, except: :index
  end

  resources :articles, only: :index


  resources :comments, only: :create

  resources :articles do
    resources :comments
  end

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :article_categories
  has_many :categories, through: :article_categories
	validates :title, presence: true
  validates :link, presence: true

  def category_name=(name)
    self.categories << Category.find_or_create_by(name: name)
  end

  def category_name
    
  end

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
	
	before_save { name.downcase! }
	validates :name, presence: true,
									 uniqueness: true
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
	
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments

  before_save { email.downcase! }
  before_save { username.downcase! }
  validates :username, presence: true, length: { within: 2..20 },
                       uniqueness: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
                    format: {with: VALID_EMAIL_REGEX },
                    uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end
	
	def self.search(username)
		if username
			username.downcase!
			self.find_by(username: username)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all
		@user = User.search(params[:user])
		if @user
			redirect_to user_path(@user)
		else
			'Username does not exist'
		end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  def new
    @user = current_user
    @article = @user.articles.build
  end

  def create
    @user = current_user
    @article = @user.articles.build(article_params)

    if @article.save
      redirect_to user_article_path(current_user, @article)
    else
      render 'new'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :link, :category_name, category_ids:[])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to user_article_path(current_user, @article)
    else
      redirect_to user_article_path(current_user, @article)
    end
  end

  def destroy

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :article_id, :user_id)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for [@user, @article] do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :link %><br />
    <%= f.text_field :link, class: "form-control" %>
  </div>

  <div class="form-group">
		<%= f.label "New Category" %>
      <%= f.text_field :category_name %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/articles/index.html.erb
<%= form_tag(articles_path, method: :get) do %>
	<%= label_tag "Find Threads by Username" %>
	<%= text_field_tag :user, params[:user] %>
	<%= submit_tag "Search", name: nil %>
<% end %>
  

<% @articles.each do |a| %>

  <div class="article row clearfix">
    <h2>
      <%= link_to a.title, user_article_path(a.user, a) %> (<%= pluralize(a.comments.count, "comment") %>)<br />
      <small class="author">created by: <%= link_to a.user.username, a.user %></small>
    </h2>
  </div>

<% end %>

app/views/articles/new.html.erb
<h1>Create New Thread</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="article row clearfix">
	<h2>
		<a href="<%= @article.link %>"><%= @article.title %></a><br />
		<small class="author"> created by: <%= link_to @article.user.username, @article.user %>
	</h2>

	<% @article.categories.each do |category| %>
		<a href="">
			<span class="label label-default"><%= category.name %></span>
		</a>
	<% end %>
</div>

<% @article.comments.each do |comment| %>
	<blockquote class="blockquote">
		<hr>
		<p>
			<%= comment.content %>
		</p>
		<footer>
			<cite title="<%= comment.user.username %>"><%= comment.user.username %></cite>
		</footer>
	</blockquote>
<% end %>

<div class="comments">
  <h5>New Comment</h5>

  <%= simple_form_for [@article, Comment.new] do |f| %>
    <div class="field">
      <%= f.text_area :content, class: "form-control" %><br />
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Noteworthy</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "New Thread", new_user_article_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign In with Github", user_github_omniauth_authorize_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Welcome, #{current_user.username}", user_path(current_user) %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Welcome Guest!", root_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noteworthy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>

    <%= render 'layouts/header' %>

    <div class="container">

      <%= yield %>

    </div>

  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<div class="user-articles">
  <% @user.articles.each do |a| %>
    <h2>
      <%= link_to a.title, user_article_path(@user, a) %> (<%= pluralize(a.comments.count, "comment") %>)
    </h2>
  <% end %>
</div>